name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure passwordless sudo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.SSH_USERNAME }} ALL=(ALL) NOPASSWD: /bin/systemctl restart socialsched-backend, /bin/systemctl restart socialsched-frontend" | sudo tee /etc/sudoers.d/socialsched

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/socialsched
            git fetch origin
            git reset --hard origin/main
            git clean -fd --force
            chmod +x deploy/deploy.sh
            ./deploy/deploy.sh
